# ==============================================
# NovaDrive Motors - DigitalOcean App Platform Spec
# ==============================================
# Deploy to: https://cloud.digitalocean.com/apps

name: car-auction-platform
region: fra  # Frankfurt, closest to Poland

services:
  - name: web
    # Build from Dockerfile
    dockerfile_path: Dockerfile

    # GitHub repository configuration
    github:
      repo: Bateristico/car-auction-platform
      branch: main
      deploy_on_push: true

    # HTTP configuration
    http_port: 3000

    # Instance configuration
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb-fixed  # $10/month

    # Routes
    routes:
      - path: /

    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 20
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      # Database - SQLite for simplicity
      - key: DATABASE_URL
        value: "file:/app/data/prod.db"

      # NextAuth configuration (Auth.js v5 uses AUTH_URL)
      - key: AUTH_URL
        scope: RUN_TIME
        value: ${APP_URL}

      - key: NEXTAUTH_URL
        scope: RUN_TIME
        value: ${APP_URL}

      - key: AUTH_TRUST_HOST
        value: "true"

      # Secrets - Configure these in DigitalOcean dashboard
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET

      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: RESEND_API_KEY
        scope: RUN_TIME
        type: SECRET

      - key: NOTIFICATION_EMAIL
        scope: RUN_TIME
        type: SECRET

      # Optional: Crawler credentials (only if using import feature)
      - key: INFORMEX_EMAIL
        scope: RUN_TIME
        type: SECRET

      - key: INFORMEX_PASSWORD
        scope: RUN_TIME
        type: SECRET

      - key: IVO_CLIENT_ID
        scope: RUN_TIME
        type: SECRET

# Alerts configuration (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
